# Generated by Django 5.1.6 on 2025-02-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('debit', 'Debit'), ('credit', 'Credit'), ('cash', 'Cash')], max_length=10, null=True),
        ),
    ]
