# Generated by Django 5.1.6 on 2025-02-12 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='item',
        ),
        migrations.AlterModelTable(
            name='receipt',
            table='receipt',
        ),
    ]
