# Generated by Django 5.1.6 on 2025-04-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="send_mail",
            field=models.BooleanField(default=True),
        ),
    ]
