# Generated by Django 5.1.6 on 2025-04-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="notification_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("receipt_added", "Receipt Added"),
                    ("group_invitation", "Group Invitation"),
                    ("system", "System Notification"),
                    ("subscription_renewal", "Subscription Renewal"),
                ],
                max_length=50,
            ),
        ),
    ]
