# Generated by Django 5.1.6 on 2025-03-03 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_subscription"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="group",
            table="groups",
        ),
    ]
