# Generated by Django 5.1.6 on 2025-02-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_item_table_alter_receipt_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.TextField(blank=True, choices=[('home', 'Home'), ('food', 'Food'), ('clothing', 'Clothing'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('fixtures', 'Fixtures'), ('furniture', 'Furniture'), ('health', 'Health'), ('beauty', 'Beauty'), ('electronics', 'Electronics')], null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.TextField(blank=True, choices=[('debit', 'Debit'), ('credit', 'Credit'), ('cash', 'Cash')], null=True),
        ),
    ]
