# Generated by Django 5.1.6 on 2025-02-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_receipt_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.TextField(blank=True, choices=[('Home', 'Home'), ('Food', 'Food'), ('Clothing', 'Clothing'), ('Utilities', 'Utilities'), ('Entertainment', 'Entertainment'), ('Fixtures', 'Fixtures'), ('Furniture', 'Furniture'), ('Health', 'Health'), ('Beauty', 'Beauty'), ('Electronics', 'Electronics')], null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Debit', 'Debit Card'), ('Credit', 'Credit Card'), ('Cash', 'Cash')], max_length=10, null=True),
        ),
    ]
