# Generated by Django 5.1.6 on 2025-03-03 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_group_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="group",
            table="group",
        ),
    ]
