# Generated by Django 5.1.6 on 2025-03-09 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="billing_interval",
        ),
    ]
