# Generated by Django 5.1.6 on 2025-03-25 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_receipt_color_folder_receipt_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='color',
        ),
    ]
