# Generated by Django 5.1.6 on 2025-03-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_receipt_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
