# Generated by Django 5.1.6 on 2025-03-26 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_receipt_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='color',
            field=models.CharField(default='#A9A9A9', max_length=7),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='color',
            field=models.CharField(default='#A9A9A9', max_length=7),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='folder',
            field=models.ForeignKey(blank=True, default='All', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='api.folder'),
        ),
    ]
