# Generated by Django 5.1.6 on 2025-02-16 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_groupmembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.group'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
