# Generated by Django 5.1.6 on 2025-03-01 17:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_receipt_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spendinganalytics',
            unique_together={('user', 'period', 'date')},
        ),
        migrations.AddField(
            model_name='spendinganalytics',
            name='category_spending',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='spendinganalytics',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='spendinganalytics',
            name='category',
        ),
    ]
