# Generated by Django 5.1.6 on 2025-03-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_folder_color_alter_receipt_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('user', 'name')},
        ),
    ]
