services:
  backend:
    image: mallisho/catalog:backend-latest
    ports:
      - "8000:8000"
    env_file:
      - ./backend/core/.env
    depends_on:
      - db

  frontend:
    image: mallisho/catalog:frontend-latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:latest
    env_file:
      - ./backend/core/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
