services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
      # local db info replaced with "abc"
    environment:
      - DEBUG=True
      - DB_NAME=catalog
      - DB_USER=abc
      - DB_PASSWORD=abc
      - DB_HOST=db  # Use container name as hostname
      - DB_PORT=5432
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

# Local db info replaced with "abc"
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=abc
      - POSTGRES_PASSWORD=abc
      - POSTGRES_DB=catalog
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
 postgres_data:
