name: CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      # Deploys locally
      # TODO: modify to deploy to remote server once setup
      - name: Set up Docker
        run: |
          docker --version
          docker-compose --version

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull latest images
        run: |
          docker pull mallisho/catalog:backend-latest
          docker pull mallisho/catalog:frontend-latest

      - name: Start containers
        run: docker-compose up -d

      # Tests not implemented yet
      # TODO: implenent tests
      # - name: Run backend tests
      #   run: |
      #     docker exec backend pytest /app/tests

      # - name: Run frontend tests
      #   run: |
      #     docker exec frontend npm test

      # - name: Stop containers after testing
      #   run: docker-compose down