name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build backend Docker image
        run: docker build -t mallisho/catalog:backend-latest ./backend

      - name: Build frontend Docker image
        run: docker build -t mallisho/catalog:frontend-latest ./frontend

      # TODO: implement tests
      # - name: Run backend tests
      #   run: docker run --rm mallisho/catalog:backend-latest pytest /app/tests

      # - name: Run frontend tests
      #   run: docker run --rm mallisho/catalog:frontend-latest npm test

      - name: Push backend image
        run: docker push mallisho/catalog:backend-latest

      - name: Push frontend image
        run: docker push mallisho/catalog:frontend-latest
