name: CI Pipeline

on:
  push:
    branches: [ "**" ] # all branche
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build backend Docker image
        run: docker build -t mallisho/catalog:backend-latest ./backend
        continue-on-error: false

      - name: Build frontend Docker image
        run: docker build -t mallisho/catalog:frontend-latest ./frontend
        continue-on-error: false

      - name: Run backend tests
        run: |
          docker run --rm mallisho/catalog:backend-latest python manage.py test
        continue-on-error: false

      - name: Run frontend tests
        run: |
          docker run --rm mallisho/catalog:frontend-latest npm test
        continue-on-error: false

      - name: Push backend image
        run: docker push mallisho/catalog:backend-latest

      - name: Push frontend image
        run: docker push mallisho/catalog:frontend-latest